plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
